apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: go-nov6-123-test 
  janus-idp.io/tekton: go-nov6-123-test
  backstage.io/kubernetes-id: go-nov6-123-test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: go-nov6-123-test
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  