apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: go-nov6-123-test-gitops
  description: This is GitOps manifest for go-nov6-123-test   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: go-nov6-123-test
    backstage.io/kubernetes-id: go-nov6-123-test 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: go-nov6-123-test   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:go-nov6-123-test
